Add yuhanjie's information by yuhanjie
SEU-NetSI/seu-netsi.github.io pull request #3
Opened 2022-06-19 06:52 UTC by mfxjx000205

Add yuhanjie's information by yuhanjie

2022-06-19 06:56 UTC, RavenLite requested changes
Nice job!
照片请换成1:1尺寸的，其他都没问题

2022-06-19 07:03 UTC, RavenLite requested changes
辛苦师弟压缩一下照片

2022-06-19 07:10 UTC, mfxjx000205 commented
已经压缩照片，但好像最大只能压缩90%，还有200K

2022-06-19 07:11 UTC, RavenLite approved these changes
Nice job!

2022-06-19 07:11 UTC, merged

2022-06-20 06:54 UTC, twinhorse commented
测试

2022-06-20 06:54 UTC, twinhorse commented
测试 @RavenLite